/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Util;

/**
 *
 * @author liam
 */
public class Prices_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Prices
     */
    public Prices_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Max_WTP_Label = new javax.swing.JLabel();
        Min_OC_Label = new javax.swing.JLabel();
        Slope_Supply_Curve_Label = new javax.swing.JLabel();
        Slope_Demand_Curve_Label = new javax.swing.JLabel();
        Max_WTP = new javax.swing.JTextField();
        Min_OC = new javax.swing.JTextField();
        JP_Graph = new javax.swing.JPanel();
        Slope_Supply_Curve = new javax.swing.JSlider();
        Slope_Demand_Curve = new javax.swing.JSlider();
        Compute_Btn = new javax.swing.JButton();
        Reset_Btn = new javax.swing.JButton();
        Title_Label = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        File_Menu = new javax.swing.JMenu();
        New_Tab_Menu_Item = new javax.swing.JMenuItem();
        Exit_Tab_Menu_Item = new javax.swing.JMenuItem();
        Info_Menu = new javax.swing.JMenu();
        Info_Menu_Item = new javax.swing.JMenuItem();
        Help_Menu_Item = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Equilibrium Supply and demand Calculator");

        Max_WTP_Label.setText("Maximum willingness to pay: ");

        Min_OC_Label.setText("Minimum opportunity cost: ");

        Slope_Supply_Curve_Label.setText("Slope Supply curve: ");

        Slope_Demand_Curve_Label.setText("Slope Demand Curve: ");

        Max_WTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Max_WTPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JP_GraphLayout = new javax.swing.GroupLayout(JP_Graph);
        JP_Graph.setLayout(JP_GraphLayout);
        JP_GraphLayout.setHorizontalGroup(
            JP_GraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JP_GraphLayout.setVerticalGroup(
            JP_GraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        Compute_Btn.setText("Compute");
        Compute_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Compute_BtnActionPerformed(evt);
            }
        });

        Reset_Btn.setText("Reset");

        Title_Label.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        Title_Label.setText("Equilibrium Supply and demand calculator");

        File_Menu.setText("File");

        New_Tab_Menu_Item.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        New_Tab_Menu_Item.setText("New Window");
        New_Tab_Menu_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_Tab_Menu_ItemActionPerformed(evt);
            }
        });
        File_Menu.add(New_Tab_Menu_Item);

        Exit_Tab_Menu_Item.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        Exit_Tab_Menu_Item.setText("Exit");
        Exit_Tab_Menu_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_Tab_Menu_ItemActionPerformed(evt);
            }
        });
        File_Menu.add(Exit_Tab_Menu_Item);

        jMenuBar1.add(File_Menu);

        Info_Menu.setText("?");

        Info_Menu_Item.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        Info_Menu_Item.setText("Information");
        Info_Menu_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Info_Menu_ItemActionPerformed(evt);
            }
        });
        Info_Menu.add(Info_Menu_Item);

        Help_Menu_Item.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        Help_Menu_Item.setText("Help");
        Help_Menu_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Help_Menu_ItemActionPerformed(evt);
            }
        });
        Info_Menu.add(Help_Menu_Item);

        jMenuBar1.add(Info_Menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JP_Graph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Min_OC_Label)
                            .addComponent(Max_WTP_Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Max_WTP, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Min_OC, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Slope_Demand_Curve_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Slope_Demand_Curve, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Slope_Supply_Curve_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Slope_Supply_Curve, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(323, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Compute_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Reset_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Title_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Slope_Supply_Curve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Max_WTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Slope_Supply_Curve_Label)
                        .addComponent(Max_WTP_Label)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Min_OC_Label)
                            .addComponent(Min_OC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Slope_Demand_Curve_Label)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Slope_Demand_Curve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Compute_Btn)
                    .addComponent(Reset_Btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JP_Graph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Max_WTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Max_WTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Max_WTPActionPerformed

    private void Compute_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Compute_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Compute_BtnActionPerformed

    private void New_Tab_Menu_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_Tab_Menu_ItemActionPerformed
        new Prices_GUI().setVisible(true);
    }//GEN-LAST:event_New_Tab_Menu_ItemActionPerformed

    private void Exit_Tab_Menu_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_Tab_Menu_ItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Exit_Tab_Menu_ItemActionPerformed

    private void Info_Menu_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Info_Menu_ItemActionPerformed
        new Me_GUI().setVisible(true);
    }//GEN-LAST:event_Info_Menu_ItemActionPerformed

    private void Help_Menu_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Help_Menu_ItemActionPerformed
        new Help_GUI().setVisible(true);
    }//GEN-LAST:event_Help_Menu_ItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prices_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prices_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prices_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prices_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prices_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Compute_Btn;
    private javax.swing.JMenuItem Exit_Tab_Menu_Item;
    private javax.swing.JMenu File_Menu;
    private javax.swing.JMenuItem Help_Menu_Item;
    private javax.swing.JMenu Info_Menu;
    private javax.swing.JMenuItem Info_Menu_Item;
    private javax.swing.JPanel JP_Graph;
    private javax.swing.JTextField Max_WTP;
    private javax.swing.JLabel Max_WTP_Label;
    private javax.swing.JTextField Min_OC;
    private javax.swing.JLabel Min_OC_Label;
    private javax.swing.JMenuItem New_Tab_Menu_Item;
    private javax.swing.JButton Reset_Btn;
    private javax.swing.JSlider Slope_Demand_Curve;
    private javax.swing.JLabel Slope_Demand_Curve_Label;
    private javax.swing.JSlider Slope_Supply_Curve;
    private javax.swing.JLabel Slope_Supply_Curve_Label;
    private javax.swing.JLabel Title_Label;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
